export const CONFIGURATION = {
    'baseServiceUrl': 'http://13.59.27.17:8080/ReportingPortalWebAPI/rest/',
    'reportingroute': 'reporting',
    'dashboard': 'dashboard',
    'nftreport': 'nhftreport',
    'enftreport': 'enftreport',
    'ogreport': 'ogreport',
    'pdareport': 'pdareport',
    'ercreport': 'ercreport',
    'empsummary': 'empsummary',
    'empeligilbility': 'empeligilbility',
    'empdemographics': 'empdemographics',
    'empbreakinservice': 'empbreakinservice',
    'addcustomer': 'addcustomer',
    'listcustomer': 'listcustomer',
    'onboardingcustomerinformation': 'onboardingcustomerinformation',
    'clientpayroll': 'clientpayroll',
    'onboardingpersonalinformation': 'onboardingpersonalinformation',
    'uploaddata': 'uploaddata',
    'aledataupload': 'aledataupload',
    'payrolldataupload': 'payrolldataupload',
    'insurancedataupload': 'insurancedataupload',
    'onezeroninefourdataupload': 'onezeroninefourdataupload',
    'onezeroninefivedataupload': 'onezeroninefivedataupload',
    'controlgroup': 'controlgroup',
    'ale': 'ale'
};
